### ISSUE TITLE
obs的包发布到nuget

### ISSUE THREAD

**Issue by xiangxiren** [huaweicloud/huaweicloud-sdk-dotnet-obs#12]
从nuget上搜索看到HuaweiCloud.SDK.OBS包名被占了，而且已经近三年没有更新过。除此之外，应该所有华为云的sdk都发到了nuget。为何不联系nuget将HuaweiCloud.SDK.OBS撤下来，然后由你们发布新的包。

**Comment by Asa-Lee** [comment]
正在规划此事项。
