### ISSUE TITLE
并发OBS下载，使用OutputStream不能正确返回完整文件

### ISSUE THREAD

**Issue by jxnchk** [huaweicloud/huaweicloud-sdk-dotnet-obs#2]
开发webapi，其中有接口通过OBS实现下载(返回GetObjectResponse.OutputStream)，当客户端并发访问时，经常出现返回的文件不能正常读取

**Comment by Asa-Lee** [comment]
请关注我们近期即将发布的新版本，在http response中需要处理网络流的场景下，需要开发者显示的调用dispose或者使用using代码块。
