### ISSUE TITLE
使用 netstandard2.0 而不是使用 .netcore 2.0

### ISSUE THREAD

**Issue by cocosip** [huaweicloud/huaweicloud-sdk-dotnet-obs#26]
使用 netstandard2.0 而不是使用 .net core2.0 , 后续的 .net core3.1,.net core5, .net 6 都能直接使用。

**Comment by liaofuda** [comment]
您好，使用 netstandard2.0 在framework框架中，存在兼容性问题，所以分开发布了，现在发了nuget，可以直接集成。
