### ISSUE TITLE
什么时候支持 .net core  3.0 +的版本

### ISSUE THREAD

**Issue by 2014fighting** [huaweicloud/huaweicloud-sdk-dotnet-obs#3]
目前用  .net  standard 2.0   的类库 引入 sdk  报版本兼容问题

**Comment by 2014fighting** [comment]
为什么sdk  不适用standard 的类库呢？

**Comment by zhongchunjin** [comment]
> 为什么sdk不适用standard的类库呢？
连Task都没有,老老实实看API封装httpClient吧  并发性能还要好点 简单的存储就几个接口

**Comment by zhongchunjin** [comment]
连Task都没有,老老实实看API封装httpClient吧 并发性能还要好点 简单的存储就几个接口

**Comment by 2014fighting** [comment]
是啊华为云这块跟阿狸差距还是很大的




| |
休止符
邮箱：ywq19920427@163.com
|

签名由 网易邮箱大师 定制

在2020年04月10日 11:36，zhongchunjin 写道：

连Task都没有,老老实实看API封装httpClient吧 并发性能还要好点 简单的存储就几个接口

**Comment by Asa-Lee** [comment]
.net core 3.x版本的sdk在规划中。
