### ISSUE TITLE
能把项目写好一点嘛？

### ISSUE THREAD

**Issue by whuanle** [huaweicloud/huaweicloud-sdk-dotnet-obs#4]
我服了。
要写SDK，就用 Standard，别用 .NET Core app 行么，生成的 Dll 用类库项目调不了。
![image](https://user-images.githubusercontent.com/2189761/89762583-4d926700-db23-11ea-86d4-b3112eef499d.png)
你这项目结构乱七八糟的：
![image](https://user-images.githubusercontent.com/2189761/89762631-61d66400-db23-11ea-8632-8e647673939f.png)

**Comment by whuanle** [comment]
Demo居然给几个文件.cs
![image](https://user-images.githubusercontent.com/2189761/89762869-df01d900-db23-11ea-8076-c864e3a2cfad.png)
就不能认真一点，把解决方案写好嘛

**Comment by Asa-Lee** [comment]
https://support.huaweicloud.com/sdk-dotnet-devg-obs/obs_25_0001.html
官网上有详细的文档说明，demo只是简单示例。
